%YAML:1.0
---
yolo_path: "model/TensorRT/yolo.engine"
armor_path: "model/TensorRT/armor_yolo.engine"
classify_path: "model/TensorRT/classify.engine"
uav_yolo_path: "model/TensorRT/RM-Plane-yolo26n-p2-2026-04-03.engine"